apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "mano.kac55@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "bzql aobp waus ihoi"
type: Opaque

# Passw0rd@1234     